---
apiVersion: v1
kind: Service
metadata:
  name: hello
  namespace: app1-ns
spec:
  selector:
    app: hello
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: http
---
