---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: app1-ns
spec:
  selector:
    app: hello
    tier: frontend
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: LoadBalancer
---